import { Check, Download, Minus, Plus, Trash2, PackageCheck } from "lucide-react";
import { money, ORDER_STAGES, PAYMENTS, productFor, unitPrice } from "@/lib/batik/catalog";
import type { BatikStudio } from "@/lib/batik/store";
import { DesignPreview } from "./StudioControls";
import { EmptyBag } from "./Collection";
export function ShoppingBag({ studio: s }: { studio: BatikStudio }) {
  return <section className="lab-section"><header><span className="lab-eyebrow">Your bag / {s.totals.units} pieces</span><h2>Good design looks better together.</h2><p>10% off when your bag contains 3 or more pieces. Free shipping from RM150 after discount.</p></header>
    {!s.cart.length ? <EmptyBag studio={s} /> : <div className="lab-checkout"><div className="lab-cart-list">{s.cart.map((x) => <article key={x.id} className="lab-cart-item"><DesignPreview design={x.design} /><div><h3>{productFor(x.design).name}</h3><p>{x.design.name}</p><small>{x.design.size} · {x.design.material}</small><button className="lab-text-button" onClick={() => s.editItem(x)}>Customise a copy ↗</button><div className="lab-quantity"><button aria-label={`Decrease ${x.design.name} quantity`} disabled={x.quantity <= 1} onClick={() => s.quantity(x.id,x.quantity-1)}><Minus size={14} /></button><output>{x.quantity}</output><button aria-label={`Increase ${x.design.name} quantity`} disabled={x.quantity >= 20} onClick={() => s.quantity(x.id,x.quantity+1)}><Plus size={14} /></button><button aria-label={`Remove ${x.design.name} from bag`} onClick={() => s.removeItem(x.id)}><Trash2 size={15} /></button></div></div><strong>{money(unitPrice(x.design)*x.quantity)}</strong></article>)}</div>
      <form className="lab-summary" onSubmit={(e) => { e.preventDefault(); s.checkout(); }}><span className="lab-eyebrow">The finishing touch</span><h3>Order summary</h3><dl><div><dt>Subtotal</dt><dd>{money(s.totals.subtotal)}</dd></div><div><dt>Bundle saving</dt><dd>−{money(s.totals.discount)}</dd></div><div><dt>Shipping</dt><dd>{s.totals.shipping ? money(s.totals.shipping) : "Free"}</dd></div><div className="lab-total"><dt>Total</dt><dd>{money(s.totals.total)}</dd></div></dl>
      <div className="lab-demo-note"><strong>Simulated checkout</strong><p>No payment is collected and no physical order is sent. Use a demo name; no card, address or banking details needed.</p></div>
      <label>Demo recipient name<input maxLength={60} value={s.name} onChange={(e) => s.setName(e.target.value)} placeholder="e.g. Batik Creator" autoComplete="off" /></label><label>Payment method (simulated)<select value={s.payment} onChange={(e) => s.setPayment(e.target.value as typeof s.payment)}>{PAYMENTS.map((p) => <option key={p}>{p}</option>)}</select></label>
      <label className="lab-check"><input type="checkbox" checked={s.acknowledged} onChange={(e) => s.setAcknowledged(e.target.checked)} /> I understand this is a mock order.</label>
      {s.checkoutError && <p className="lab-error" role="alert">{s.checkoutError}</p>}<button className="lab-button lab-primary" type="submit">Place mock order <Check size={17} /></button></form></div>}
  </section>;
}
export function Orders({ studio: s }: { studio: BatikStudio }) {
  return <section className="lab-section"><header><span className="lab-eyebrow">From your imagination to the doorstep</span><h2>Follow the journey.</h2><p>Order history is saved in this browser. Every stage below is a simulation you control.</p></header>
    {!s.orders.length ? <div className="lab-empty"><PackageCheck size={38} /><h3>Your story is still being made.</h3><p>Place a mock order to explore the full tracking journey.</p><button className="lab-button" onClick={() => s.setTab("bag")}>Open your bag</button></div> : <div className="lab-orders">{s.orders.map((o) => <article key={o.id}><div className="lab-order-heading"><div><span className="lab-eyebrow">{o.id} · {new Date(o.date).toLocaleDateString("en-MY")}</span><h3>{o.progress === 4 ? `Terima kasih, ${o.name}!` : `Made for ${o.name}.`}</h3></div><strong>{money(o.total)}</strong></div><div className="lab-order-products">{o.items.map((x) => <figure key={x.id}><DesignPreview design={x.design} /><figcaption>{x.quantity} × {productFor(x.design).name}<small>{x.design.name} · {x.design.size} · {x.design.material}</small></figcaption></figure>)}</div><ol className="lab-tracking">{ORDER_STAGES.map((stage,i) => <li key={stage} data-done={i <= o.progress} aria-current={i === o.progress ? "step" : undefined}><span>{i <= o.progress ? <Check size={15} /> : i+1}</span>{stage}</li>)}</ol><div className="lab-actions"><button className="lab-button lab-primary" disabled={o.progress === 4} onClick={() => s.advance(o.id)}>{o.progress === 4 ? "Delivered in the demo" : "Simulate next update"}</button><button className="lab-button" onClick={() => s.receipt(o)}><Download size={16} /> Download receipt</button><span className="lab-help">{o.payment} · No payment taken</span></div></article>)}</div>}
  </section>;
}
