import type { ProjectState, PromptEntry, SectionTask, ContentSample } from "./types";

const task = (): SectionTask => ({
  status: "not_started",
  assignees: [],
  reviewerNotes: "",
  promptLog: "",
  verified: false,
});

const p = (
  id: string,
  title: string,
  category: PromptEntry["category"],
  section: PromptEntry["section"],
  purpose: string,
  text: string,
  variables = "",
): PromptEntry => ({ id, title, category, section, purpose, text, variables, notes: "" });

const prompts: PromptEntry[] = [
  // Ideation (7)
  p("p1", "10 startup ideas", "Ideation", "s1", "Brainstorm a wide idea pool before narrowing.", "Act as a Malaysian startup mentor. Suggest 10 distinct startup ideas for university students in {city}. Each idea must solve a concrete everyday problem, be demonstrable as a small website prototype, and avoid government services and generic chatbots. Return a table: name, one-line pitch, target customer, how it makes money.", "{city}"),
  p("p2", "Pros and cons shortlist", "Ideation", "s1", "Compare shortlisted ideas fairly.", "For these 5 ideas: {ideas}. Give 3 pros and 3 cons each, then score appeal, feasibility and prototype potential from 1 to 5. Explain each score in one sentence. Do not invent market statistics.", "{ideas}"),
  p("p3", "Company name options", "Ideation", "s1", "Generate brand name alternatives.", "Our company is called Tech Ventura. Suggest 8 product names for {product}. They should be short, easy to pronounce in Malay and English, and not already a famous brand. Give the meaning behind each.", "{product}"),
  p("p4", "Tagline generator", "Ideation", "s1", "Short memorable taglines.", "Write 10 taglines (max 6 words) for {product}, a {one_line_pitch}. Tone: playful, proud of Malaysian craft, modern. Mark your top 2 and explain why.", "{product}, {one_line_pitch}"),
  p("p5", "Mission, vision, values", "Ideation", "s1", "Draft identity statements.", "Draft a mission (1 sentence), vision (1 sentence) and 4 core values with one-line explanations for Tech Ventura, which makes {product}. Avoid buzzwords like 'synergy' and 'disrupt'.", "{product}"),
  p("p6", "Founding story", "Ideation", "s2", "Narrative for the company profile.", "Write a 120-word fictional founding story for Tech Ventura, started by 5 university students in {city}. Make it clear this is fictional. Mention the customer problem that inspired {product}.", "{city}, {product}"),
  p("p7", "Product feature brainstorm", "Ideation", "s4", "Expand product features.", "List 10 possible features for {product}. For each, give the user benefit and rate build effort (low/medium/high) for a student prototype. Recommend the 5 for an MVP.", "{product}"),
  // Analysis (7)
  p("p8", "Problem statement", "Analysis", "s3", "Frame the customer problem.", "Write a clear problem statement for {target_customer} in Malaysia who want {need}. Use the format: who, what problem, why it matters, current workaround. Flag any assumption with [ASSUMPTION].", "{target_customer}, {need}"),
  p("p9", "Market analysis with assumptions", "Analysis", "s3", "Structured market view without fake stats.", "Outline a market analysis for {product} in Malaysia: segments, trends, buying drivers, barriers. Do not state numbers as facts. Where a number would help, write it as a labelled assumption with how we could verify it.", "{product}"),
  p("p10", "Competitor matrix", "Analysis", "s3", "Compare alternatives.", "Build a competitor comparison for {product} against: marketplace print shops, traditional batik boutiques, global print-on-demand apps, DIY. Columns: offer, typical price in RM (estimate), customisation, local identity, weakness.", "{product}"),
  p("p11", "SWOT", "Analysis", "s3", "SWOT analysis.", "Create a SWOT for Tech Ventura's {product}, a student-founded startup in Malaysia. 4 bullet points per quadrant, each under 15 words.", "{product}"),
  p("p12", "Financial projection check", "Analysis", "s3", "Sanity-check the numbers.", "Here is our 3-year projection: {table}. Check the maths, point out unrealistic assumptions, and suggest safer ranges. Show all calculations.", "{table}"),
  p("p13", "Demographic segmentation", "Analysis", "s5", "Define target segments.", "Segment the Malaysian market for {product} by age, gender, income (RM), location, interests, needs and behaviours. Label everything as a hypothesis to validate.", "{product}"),
  p("p14", "Persona builder", "Analysis", "s5", "Create persona composites.", "Create 3 customer persona composites for {product} in Malaysia. For each: name, age, location, occupation, monthly income in RM, goals, frustrations, behaviours, and a quote. State clearly they are fictional composites.", "{product}"),
  // Marketing (7)
  p("p15", "Journey map", "Marketing", "s5", "Map the customer journey.", "Create a customer journey map for {persona} buying {product}: stages Awareness, Consideration, Design, Purchase, Delivery, Share. For each: actions, questions, pain points, touchpoints, opportunities.", "{persona}, {product}"),
  p("p16", "Social strategy", "Marketing", "s6", "Overall social plan.", "Draft a 3-month social media strategy for {product} targeting {segment} in Malaysia. Include goals, platforms and why, brand voice, and 3 measurable KPIs.", "{product}, {segment}"),
  p("p17", "Content pillars", "Marketing", "s6", "Define recurring themes.", "Suggest 4 content pillars for {product}. Each needs a name, purpose, and 3 example post ideas.", "{product}"),
  p("p18", "Instagram captions", "Marketing", "s6", "Write IG posts.", "Write 5 Instagram captions for {product}. Mix Malay and English naturally (Manglish is fine). Each under 60 words with a CTA and 5 hashtags.", "{product}"),
  p("p19", "TikTok scripts", "Marketing", "s6", "Short video scripts.", "Write 3 TikTok scripts (20 to 30 seconds) for {product}. Format: hook (0 to 3s), scenes with on-screen text, voiceover, CTA. Trend-friendly but brand-safe.", "{product}"),
  p("p20", "Facebook ads", "Marketing", "s6", "Paid ad copy.", "Write 3 Facebook ads for {product} targeting parents and gift buyers aged 30 to 45 in Klang Valley and Penang. Each: headline, primary text, CTA button.", "{product}"),
  p("p21", "LinkedIn posts", "Marketing", "s6", "Founder-voice posts.", "Write 2 LinkedIn posts from a Tech Ventura co-founder about building {product} as students: one about the problem, one about lessons from prototyping. 120 words each.", "{product}"),
  // Image generation (5)
  p("p22", "Logo concept", "Image generation", "s1", "Create a logo.", "Minimal flat vector logo for 'Tech Ventura', monogram TV formed from a stylised batik parang wave, deep indigo and warm gold on off-white, no gradients, centered, high contrast.", ""),
  p("p23", "Mood board", "Image generation", "s1", "Brand mood board.", "Mood board collage for a modern Malaysian batik design brand: indigo dye textures, canting tool, hands drawing wax lines, clean white studio, gold accents, young creators, soft daylight.", ""),
  p("p24", "Product mockup", "Image generation", "s4", "Product visuals.", "Studio product photo of a canvas tote bag printed with a custom geometric batik pattern in {colours}, on a light concrete surface, soft shadow, 4:5 ratio.", "{colours}"),
  p("p25", "App screen mockup", "Image generation", "s4", "Show the app.", "Clean smartphone mockup showing a batik pattern designer app, motif picker at the bottom, live preview of a tee shirt, dark UI with blue accent, isometric angle.", ""),
  p("p26", "Social post visual", "Image generation", "s6", "IG visual.", "Flat lay of three products (tote, tee, scarf) with matching custom batik prints in {colours}, Malaysian festive props (ketupat, kuih), top-down, bright.", "{colours}"),
  // Technical/prototype (4)
  p("p27", "Prototype user flow", "Technical/prototype", "s4", "Plan the demo flow.", "Describe the minimum user flow for a web prototype of {product}: screens, what the user taps, and what state changes. Keep it to 4 screens.", "{product}"),
  p("p28", "Pattern generator logic", "Technical/prototype", "s4", "Build the core interaction.", "Write a React component that renders a repeating SVG batik-style motif (parang, kawung, bunga raya) with two colour props and a scale slider. Keep it dependency-free.", ""),
  p("p29", "Pricing calculator", "Technical/prototype", "s4", "Checkout logic.", "Write a TypeScript function that returns the RM price for a product type, size and quantity with a 10% discount at 3+ items. Include unit tests.", ""),
  p("p30", "Presentation speaker notes", "Technical/prototype", "s8", "Rehearsal help.", "Here is our presentation outline with timings: {outline}. Write speaker notes for each part, flag where we run over 40 minutes, and suggest transitions.", "{outline}"),
];

const sample = (
  id: string,
  platform: ContentSample["platform"],
  title: string,
  body: string,
  cta: string,
  imagePrompt: string,
): ContentSample => ({ id, platform, title, body, cta, imagePrompt, imageUrl: "" });

export const SEED_VERSION = 1;

export function createSeed(): ProjectState {
  return {
    version: SEED_VERSION,
    updatedAt: new Date().toISOString(),
    members: [
      { id: "m1", name: "Member 1" },
      { id: "m2", name: "Member 2" },
      { id: "m3", name: "Member 3" },
      { id: "m4", name: "Member 4" },
      { id: "m5", name: "Member 5" },
    ],
    tasks: { s1: task(), s2: task(), s3: task(), s4: task(), s5: task(), s6: task(), s7: task(), s8: task() },
    touched: {},
    company: {
      ideas: [
        { id: "i1", name: "BatikLab", summary: "Design your own batik pattern on your phone and get it printed on a tote, tee or scarf.", pros: "Very visual, proud local identity, easy to demo", cons: "Needs a reliable print partner", shortlisted: true },
        { id: "i2", name: "Makan Match", summary: "Friends swipe on nearby food spots and the app picks where the group eats.", pros: "Fun, everyday problem, viral potential", cons: "Hard to monetise early", shortlisted: true },
        { id: "i3", name: "ThriftLoop", summary: "Pre-loved fashion swap between university students.", pros: "Sustainable, clear campus audience", cons: "Trust and logistics issues", shortlisted: true },
        { id: "i4", name: "RakSewa", summary: "Campus rental for cameras, camping and event gear.", pros: "Saves students money", cons: "Damage and insurance risk", shortlisted: true },
        { id: "i5", name: "Balkoni", summary: "Smart balcony herb-garden kits for condo dwellers.", pros: "Physical product, recurring refills", cons: "Hardware costs, slow to prototype", shortlisted: true },
        { id: "i6", name: "StudyDuet", summary: "Match study partners by course and timetable.", pros: "Clear student need", cons: "Crowded space", shortlisted: false },
        { id: "i7", name: "KuihBox", summary: "Monthly box of traditional kuih from small home bakers.", pros: "Supports home businesses", cons: "Short shelf life", shortlisted: false },
        { id: "i8", name: "FitKampung", summary: "Gamified outdoor fitness trails in local parks.", pros: "Healthy, community", cons: "Needs park partners", shortlisted: false },
        { id: "i9", name: "PetJaga", summary: "Book trusted neighbours to pet-sit during balik kampung.", pros: "Seasonal demand spike", cons: "Trust and safety", shortlisted: false },
        { id: "i10", name: "SoundKedai", summary: "Marketplace for local indie musicians to sell stems and beats.", pros: "Creative niche", cons: "Small market", shortlisted: false },
      ],
      concepts: [
        { id: "i1", name: "BatikLab", pitch: "A mobile batik pattern studio that turns anyone's design into a printed product.", customers: "Students, young professionals, gift buyers, corporate event teams", monetisation: "Margin on each printed product, plus premium motif packs and bulk corporate orders", appeal: 5, feasibility: 4, prototype: 5 },
        { id: "i2", name: "Makan Match", pitch: "Tinder-style swiping to end the 'makan mana?' debate.", customers: "Friend groups and colleagues aged 18 to 35", monetisation: "Promoted restaurant placements and vouchers", appeal: 5, feasibility: 4, prototype: 4 },
        { id: "i3", name: "ThriftLoop", pitch: "Swap, not shop: pre-loved fashion trades on campus.", customers: "University students", monetisation: "Small swap fee and campus pop-up events", appeal: 4, feasibility: 3, prototype: 3 },
        { id: "i4", name: "RakSewa", pitch: "Rent the gear you need for the weekend, from students nearby.", customers: "Students and young hobbyists", monetisation: "Commission on each rental plus deposit protection fee", appeal: 3, feasibility: 3, prototype: 3 },
        { id: "i5", name: "Balkoni", pitch: "A plug-and-grow herb kit for small condo balconies.", customers: "Urban condo residents aged 25 to 45", monetisation: "Kit sales plus seed and nutrient refill subscription", appeal: 4, feasibility: 2, prototype: 2 },
      ],
      selectedConceptId: "i1",
      rationale: "BatikLab scored highest on appeal and prototype potential. It is product-led, visually exciting to demo live, celebrates Malaysian heritage, and has a simple money model (margin per printed item). Placeholder concept: the group may replace it later.",
      name: "Tech Ventura",
      productName: "BatikLab",
      tagline: "Your pattern. Your pride.",
      mission: "Make it effortless for anyone in Malaysia to design and own batik that feels personal.",
      vision: "A new generation wearing, gifting and sharing batik they designed themselves.",
      values: ["Craft with respect: honour traditional motifs and artisans", "Playful creativity: design should feel like play", "Local first: print and source in Malaysia", "Honest pricing: clear RM prices, no hidden fees"],
      palette: [
        { id: "c1", name: "Indigo Tinta", hex: "#1e2a78" },
        { id: "c2", name: "Emas Songket", hex: "#d4a24c" },
        { id: "c3", name: "Merah Bunga Raya", hex: "#c8323c" },
        { id: "c4", name: "Hijau Pandan", hex: "#3f8f5a" },
        { id: "c5", name: "Kain Putih", hex: "#f4efe6" },
      ],
      logo: { id: "logo", url: "", caption: "Primary logo", prompt: "Minimal flat vector logo for 'Tech Ventura', monogram TV formed from a stylised batik parang wave, deep indigo and warm gold on off-white, no gradients." },
      moodboard: [
        { id: "mb1", url: "", caption: "Indigo dye textures", prompt: "Close-up of hand-dyed indigo batik fabric with visible wax crackle, soft daylight." },
        { id: "mb2", url: "", caption: "Canting in action", prompt: "Hands holding a copper canting tool drawing hot wax lines on white cotton, shallow depth of field." },
        { id: "mb3", url: "", caption: "Young creators", prompt: "Young Malaysian students laughing while designing on phones in a bright cafe, batik tote on the table." },
      ],
      background: "Tech Ventura is a fictional student-founded startup based in Shah Alam, Selangor. It builds playful design tools that connect young Malaysians with local craft.",
      foundingStory: "Fictional: During a group assignment, five friends struggled to find a meaningful Hari Raya gift for their lecturer. Custom batik was too expensive and too slow; generic print shops felt soulless. They sketched a phone app that lets anyone mix traditional motifs and order a printed tote within a week. That sketch became BatikLab, the first product of Tech Ventura.",
      founders: [
        { id: "f1", name: "Aina Rahman (fictional)", role: "Co-founder, product and design", bio: "Final-year design student who loves turning heritage motifs into modern graphics." },
        { id: "f2", name: "Daniel Lim (fictional)", role: "Co-founder, engineering", bio: "Computer science student who built the pattern engine prototype." },
        { id: "f3", name: "Priya Nair (fictional)", role: "Co-founder, operations", bio: "Business student managing print partners and delivery." },
        { id: "f4", name: "Hafiz Azmi (fictional)", role: "Co-founder, marketing", bio: "Runs a 20k-follower food TikTok (fictional) and leads social campaigns." },
        { id: "f5", name: "Mei Ling Tan (fictional)", role: "Co-founder, finance", bio: "Accounting student who owns pricing, costing and the financial model." },
      ],
      orgStructure: "Flat founding team of 5 co-founders. Workstreams: Product and design, Engineering, Operations and print partners, Marketing and community, Finance. External: 2 partner print shops in Klang Valley, freelance batik artisans for premium motif packs (assumption).",
      services: "1. BatikLab app: design a pattern from motif, colour and scale controls.\n2. Printed products: tote bag, tee, scarf.\n3. Corporate and event orders: bulk custom batik for teams and weddings.\n4. Premium motif packs co-created with artisans.",
      usp: "The only Malaysian tool where anyone can design authentic-looking batik in under 2 minutes and receive a locally printed product within a week (claim to be validated).",
    },
    business: {
      problem: "Young Malaysians want personal, locally meaningful items for themselves and as gifts, but hand-made custom batik is expensive and slow, and generic print-on-demand designs feel impersonal. [ASSUMPTION, to validate through a 30-person survey]",
      solution: "BatikLab is a mobile-first design studio: choose a traditional motif, pick colours, preview it live on a product, and order. Designs are printed by Malaysian partners and delivered in 5 to 7 days.",
      market: "Primary: students and young professionals (18 to 30) in Klang Valley, Penang and Johor Bahru buying for themselves and gifts. Secondary: corporate teams and event planners needing branded batik. Seasonal peaks around Hari Raya, Merdeka, Deepavali, Chinese New Year and graduation. All market sizes are unverified assumptions.",
      assumptions: [
        "Average order value around RM62 (assumption)",
        "Print partner cost RM24 to RM28 per unit (assumption, to confirm with quotes)",
        "3,000 units sold in Year 1 (assumption)",
        "Most sales via Instagram and TikTok referral (assumption)",
      ],
      competitors: [
        { id: "k1", name: "Marketplace print shops", offer: "Print any uploaded image", price: "RM25 to RM45", customisation: "High, but no design help", localIdentity: "Low", weakness: "Customer must already have a design" },
        { id: "k2", name: "Traditional batik boutiques", offer: "Hand-made batik pieces", price: "RM120 to RM600", customisation: "Low to medium", localIdentity: "Very high", weakness: "Expensive and slow for custom orders" },
        { id: "k3", name: "Global print-on-demand apps", offer: "Templates and printing", price: "RM60 to RM120 plus shipping", customisation: "Medium", localIdentity: "None", weakness: "Long overseas delivery, no batik motifs" },
        { id: "k4", name: "BatikLab (us)", offer: "Guided batik design plus print", price: "RM49 to RM89", customisation: "High, guided", localIdentity: "High", weakness: "New brand, unproven quality" },
      ],
      swot: {
        strengths: ["Fun, fast design experience", "Strong Malaysian identity", "Low upfront cost (print-on-demand)", "Highly shareable designs"],
        weaknesses: ["No brand recognition yet", "Dependent on print partners", "Small founding team", "Digital motifs may feel less authentic"],
        opportunities: ["Festive gifting seasons", "Corporate and wedding bulk orders", "Collabs with artisans and influencers", "Tourist souvenir market"],
        threats: ["Copycat apps", "Print quality complaints", "Rising courier costs", "Cultural sensitivity if motifs are misused"],
      },
      revenueModel: "1. Product margin on each printed item (tote RM49, tee RM69, scarf RM89).\n2. Premium motif packs at RM9.90 each, revenue shared 50/50 with artisans.\n3. Bulk corporate orders with tiered pricing.\nAll prices are assumptions.",
      costStructure: "Variable: printing and blanks (per unit), packaging, payment fees (around 3%), courier.\nFixed: app hosting and tools, design software, part-time customer support, small studio rent from Year 2.\nMarketing: influencer seeding, paid social ads, campus pop-ups.",
      projection: [
        { id: "y1", label: "Year 1", units: 3000, avgPrice: 62, cogsPerUnit: 28, fixedCosts: 90000, marketing: 40000 },
        { id: "y2", label: "Year 2", units: 9000, avgPrice: 64, cogsPerUnit: 26, fixedCosts: 120000, marketing: 70000 },
        { id: "y3", label: "Year 3", units: 18000, avgPrice: 65, cogsPerUnit: 24, fixedCosts: 180000, marketing: 110000 },
      ],
    },
    product: {
      concept: "BatikLab: a mobile batik pattern studio. Placeholder product for Tech Ventura, to be confirmed by the group.",
      description: "Users pick a traditional-inspired motif (Parang, Kawung, Bunga Raya, Pucuk Rebung), choose two brand-safe colours, adjust scale, and instantly preview the design on a tote, tee or scarf. They choose size and quantity, see the RM price, and place an order printed locally.",
      features: [
        { id: "ft1", title: "Motif picker", benefit: "Start from authentic-looking patterns, no drawing skill needed" },
        { id: "ft2", title: "Live product preview", benefit: "See exactly what you will receive before paying" },
        { id: "ft3", title: "Colour pairs", benefit: "Curated palettes that always look good together" },
        { id: "ft4", title: "Clear RM pricing", benefit: "Price updates instantly, with bulk discount at 3+ items" },
        { id: "ft5", title: "Order tracking", benefit: "Know when your design is printed and shipped" },
      ],
      benefits: ["Personal gifts in minutes", "Supports local printers and artisans", "Affordable compared to hand-made custom batik"],
      differentiators: ["Batik-specific motif engine, not generic templates", "Local print and delivery in 5 to 7 days (target)", "Artisan-co-created premium motifs"],
      mockups: [
        { id: "mk1", url: "", caption: "Tote bag with Parang motif", prompt: "Studio product photo of a canvas tote bag printed with a geometric parang batik pattern in indigo and gold, light concrete surface, soft shadow, 4:5." },
        { id: "mk2", url: "", caption: "App screen", prompt: "Smartphone mockup of a batik pattern designer app with motif picker and tee preview, dark UI with blue accent." },
      ],
    },
    customers: {
      segments: [
        { label: "Age", value: "Core 18 to 30; secondary 30 to 45 gift buyers (hypothesis)" },
        { label: "Gender", value: "All genders; early buyers expected slightly more female for gifting (hypothesis)" },
        { label: "Income", value: "Students RM500 to RM1,500 allowance; young professionals RM3,000 to RM6,000 per month (assumption)" },
        { label: "Location", value: "Klang Valley, Penang, Johor Bahru first; nationwide delivery later" },
        { label: "Interests", value: "Local fashion, gifting, festive seasons, DIY and design, social media trends" },
        { label: "Needs", value: "Meaningful affordable gifts, self-expression, fast delivery, trust in quality" },
        { label: "Behaviours", value: "Discover on TikTok and Instagram, pay via e-wallet or FPX, buy close to festive dates" },
      ],
      personas: [
        { id: "pe1", name: "Nurul, 21 (persona composite)", age: "21", location: "Shah Alam, Selangor", occupation: "Mass communication student", income: "RM900 allowance per month", goals: "Unique gifts for friends, express her style", frustrations: "Custom items take too long or cost too much", behaviours: "Scrolls TikTok daily, buys with Touch 'n Go eWallet", quote: "I want something no one else has, but I only have RM60." },
        { id: "pe2", name: "Kevin, 28 (persona composite)", age: "28", location: "George Town, Penang", occupation: "UX designer at a startup", income: "RM5,200 per month", goals: "Team merch for company events that feels local", frustrations: "Bulk suppliers need large minimum orders", behaviours: "Uses LinkedIn and Instagram, pays by corporate card", quote: "Our team wants merch that actually looks Malaysian, not generic." },
        { id: "pe3", name: "Puan Salmah, 42 (persona composite)", age: "42", location: "Johor Bahru, Johor", occupation: "Teacher and event organiser", income: "RM4,500 per month", goals: "Matching batik for family Raya photos and school events", frustrations: "Hard to coordinate sizes and colours for many people", behaviours: "Active on Facebook and WhatsApp groups", quote: "If I can see it first, I will order for the whole family." },
      ],
      journey: [
        { id: "j1", stage: "Awareness", actions: "Sees a friend's custom tote on TikTok", questions: "What is this? Where can I get one?", pains: "Unsure if it is legit", touchpoints: "TikTok, Instagram Stories", opportunities: "Creator content with 'design with me' format" },
        { id: "j2", stage: "Consideration", actions: "Visits website, checks prices", questions: "Is it expensive? How long is delivery?", pains: "Unclear shipping times", touchpoints: "Website, reviews", opportunities: "Show RM price and delivery date up front" },
        { id: "j3", stage: "Design", actions: "Plays with motifs and colours", questions: "Will it look good printed?", pains: "Fear of ugly result", touchpoints: "BatikLab designer", opportunities: "Curated colour pairs, live preview" },
        { id: "j4", stage: "Purchase", actions: "Chooses size, pays", questions: "Is payment safe?", pains: "Extra fees at checkout", touchpoints: "Checkout, FPX, e-wallet", opportunities: "All-in pricing, bulk discount" },
        { id: "j5", stage: "Delivery", actions: "Tracks order, receives item", questions: "When will it arrive?", pains: "No updates", touchpoints: "Order tracking, WhatsApp updates", opportunities: "Status timeline with print photos" },
        { id: "j6", stage: "Share", actions: "Posts photo with product", questions: "Can I get a discount for sharing?", pains: "No reward", touchpoints: "Instagram, TikTok", opportunities: "Referral code and repost feature" },
      ],
    },
    marketing: {
      strategy: "Goal for first 3 months (assumption): 5,000 followers, 300 orders. Lead with TikTok and Instagram for discovery using 'design with me' videos; use Facebook for parents and gift buyers; LinkedIn for corporate orders. Brand voice: warm, playful, proud of Malaysian craft, mixing Malay and English naturally.",
      pillars: [
        { id: "pl1", title: "Design with me", description: "Short videos of real users creating patterns in the app" },
        { id: "pl2", title: "Motif stories", description: "The meaning behind Parang, Kawung, Bunga Raya and more" },
        { id: "pl3", title: "Gift moments", description: "Festive and birthday gifting ideas" },
        { id: "pl4", title: "Behind the print", description: "Local print partners and quality checks" },
      ],
      schedule: [
        { id: "sc1", day: "Monday", platform: "Instagram", content: "Motif story carousel" },
        { id: "sc2", day: "Tuesday", platform: "TikTok", content: "Design with me video" },
        { id: "sc3", day: "Wednesday", platform: "Facebook", content: "Gift idea post and ad refresh" },
        { id: "sc4", day: "Thursday", platform: "TikTok", content: "Behind the print" },
        { id: "sc5", day: "Friday", platform: "Instagram", content: "Customer feature repost" },
        { id: "sc6", day: "Saturday", platform: "LinkedIn", content: "Founder update (fortnightly)" },
      ],
      influencer: "Seed 10 micro-creators (5k to 50k followers) in fashion, campus life and food; give each a free product and a unique code. Budget assumption: RM6,000 for Year 1. Prefer creators from Klang Valley, Penang and JB.",
      paid: "Meta ads for festive seasons, targeting ages 18 to 45 in Klang Valley, Penang and JB, interests gifting and local fashion. TikTok Spark Ads to boost top-performing creator videos. Budget assumption: RM2,500 per month in peak months. Track cost per order.",
      samples: [
        sample("ig1", "instagram", "Your pattern, your pride", "Batik, but make it yours. Pick a motif, pick your colours, and we print it right here in Malaysia. Siap dalam seminggu!", "Design yours at the link in bio #BatikLab #BatikMalaysia #KitaPunya #HadiahRaya #LocalPride", "Flat lay of a custom indigo and gold batik tote on a rattan mat, bright daylight."),
        sample("ig2", "instagram", "Motif story: Parang", "The Parang motif flows like unbroken waves, a symbol of never giving up. Now you can wear it your way.", "Swipe to see 3 colour pairs #MotifStory #BatikLab #Warisan #BatikModern #MadeInMalaysia", "Carousel cover: close-up of parang wave pattern in red and cream."),
        sample("ig3", "instagram", "Raya matching set", "Satu keluarga, satu motif. Design once, order for everyone in different sizes.", "Order before 15 March for Raya delivery #RayaOOTD #BatikLab #MatchingFamily #HariRaya #Batik", "Family of five in matching green and gold custom batik tees, festive home setting."),
        sample("ig4", "instagram", "Behind the print", "Meet our partner print shop in Klang. Every order is checked by hand before it ships.", "Tag someone who loves local #BehindThePrint #SupportLocal #BatikLab #Klang #QualityCheck", "Print shop worker inspecting a freshly printed batik scarf, warm lighting."),
        sample("ig5", "instagram", "Customer feature", "@nurul.designs (fictional) made this Bunga Raya tote in 90 seconds. Honestly, obsessed.", "Share your design with #MadeOnBatikLab #BatikLab #CustomerLove #ToteBag #Malaysia", "Young woman holding a red hibiscus-patterned tote outside a cafe in Shah Alam."),
        sample("tt1", "tiktok", "Design with me in 60 seconds", "Hook (0 to 3s): 'Budget RM50, need a Raya gift, go!'\nScene 1: Open BatikLab, pick Kawung motif (text: step 1).\nScene 2: Swipe colour pairs, land on gold and indigo (text: step 2).\nScene 3: Preview on tote, tap order (text: RM49 all in).\nVO: 'Siap. Gift sorted.'", "Link in bio, first 100 orders free shipping", "Vertical phone screen recording with hands visible, upbeat."),
        sample("tt2", "tiktok", "Guess the motif", "Hook: 'Only true Malaysians can name this motif.'\nScenes: zoom-in on 3 motifs, pause for guess, reveal name and meaning.\nEnd: 'Design with it on BatikLab.'", "Comment your score", "Extreme close-up of batik motifs revealed one by one."),
        sample("tt3", "tiktok", "Unboxing the print", "Hook: 'I designed this on my phone last Monday.'\nScene 1: Courier arrives. Scene 2: Unbox tee. Scene 3: Side by side with app preview.\nVO: 'Same same, not different.'", "Try it: link in bio", "Unboxing on a bed, natural light, tee held up next to phone preview."),
        sample("fb1", "facebook", "Raya gift, sorted in 2 minutes", "Design a matching batik set for the whole family. Printed in Malaysia, delivered in 5 to 7 days. From RM49.", "Shop now", "Mother and daughter in matching custom batik scarves, festive background."),
        sample("fb2", "facebook", "Teacher's Day idea", "Give your cikgu something personal. Design a batik tote with their favourite colours.", "Learn more", "Batik tote with a handwritten thank-you card on a teacher's desk."),
        sample("fb3", "facebook", "Company event merch", "Custom batik tees for your team, no huge minimum order. Bulk discount from 3 items.", "Get quote", "Office team posing in matching blue batik tees."),
        sample("li1", "linkedin", "Why we are building BatikLab", "As students, we noticed a gap: people love batik but custom batik is slow and costly. We are building a tool that lets anyone design batik in minutes and get it printed locally. Here is what we learned from our first 30 user interviews (planned).", "Follow our journey", "Founding team around a laptop with printed batik samples."),
        sample("li2", "linkedin", "Lessons from prototyping", "Three lessons from building our first prototype: 1. Show the price early. 2. Fewer, better colour choices convert more (hypothesis). 3. A live preview beats a long description. What would you add?", "Share your thoughts", "Whiteboard with user flow sketches and sticky notes."),
      ],
    },
    prompts,
    usedPrompts: [],
    presentation: [
      { key: "opening", title: "Opening", minutes: 2, speakerIds: ["m1"], keyPoints: "Welcome, team, agenda", transition: "Let us start with who we are.", speakerNotes: "" },
      { key: "company", title: "Company introduction", minutes: 5, speakerIds: ["m1"], keyPoints: "Identity, mission, founders, USP", transition: "So how do we make this a business?", speakerNotes: "" },
      { key: "business", title: "Business plan", minutes: 6, speakerIds: ["m2"], keyPoints: "Problem, market, competitors, SWOT, financials", transition: "Let us show you the product itself.", speakerNotes: "" },
      { key: "product", title: "Product demonstration", minutes: 6, speakerIds: ["m3"], keyPoints: "Live demo of the design and order flow", transition: "Now, how will people find us?", speakerNotes: "" },
      { key: "marketing", title: "Marketing plan", minutes: 5, speakerIds: ["m4"], keyPoints: "Strategy, pillars, content samples", transition: "Who exactly are we talking to?", speakerNotes: "" },
      { key: "demographics", title: "Target demographics", minutes: 4, speakerIds: ["m4"], keyPoints: "Segments, personas, journey", transition: "Finally, how AI powered all of this.", speakerNotes: "" },
      { key: "prompts", title: "AI prompt engineering (main highlight)", minutes: 9, speakerIds: ["m5", "m2"], keyPoints: "Prompt design, iteration, examples, limitations, how outputs were checked", transition: "To wrap up.", speakerNotes: "" },
      { key: "conclusion", title: "Conclusion", minutes: 1, speakerIds: ["m1"], keyPoints: "Recap and next steps", transition: "We are happy to take questions.", speakerNotes: "" },
      { key: "qa", title: "Q&A", minutes: 2, speakerIds: ["m1", "m2", "m3", "m4", "m5"], keyPoints: "Open questions", transition: "", speakerNotes: "" },
    ],
  };
}
